# Generated by Django 5.2.6 on 2025-10-15 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='is_completed',
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('done', 'Done'), ('in_progress', 'In progress'), ('not_started', 'Not started')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
